import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeToggleButton from "../components/ThemeToggleButton"; // Import the client component
import Header from "../components/sections/Header";
import BottomNavigation from "../components/sections/BottomNavigation";
import Footer from "../components/sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-[Iranian Sans]">
        <ThemeProvider>
          <Header />
          {children}
          <ThemeToggleButton />
          <div className="flex md:hidden">
            <BottomNavigation />
          </div>
          <Footer />
          <div className="flex md:hidden h-20 "></div>
        </ThemeProvider>
      </body>
    </html>
  );
}
